### ISSUE TITLE
gc_limbo is not thread-safe?

### ISSUE THREAD

**Issue by charles-salvia** [rmind/libqsbr#2]
I've been reading over the source for **libqsbr** - it looks like a great library which I'd like to use in a few applications, however I'm confused about one aspect of the design.  Specifically, regarding the code that inserts removed elements into the limbo list - why is this code not thread-safe?  I mean, the code for `gc_limbo`, for example, does not use any memory barriers or atomic instructions when it adds the removed element into the limbo list.  And the limbo list is not thread-local.  Yet, the example in the README file indicates that we can call `gc_limbo` from any random worker thread.  So how is this possible?  

It would seem that since `gc_limbo` does not use memory barriers or atomic instructions, it would only be safe to call it from _one thread_ - perhaps a specially designated "reclamation thread" or something - except the README seems to imply we can call `gc_limbo` from _any_ arbitrary worker thread.  I'm very confused about this issue, and would appreciate any insight into how `gc_limbo` is supposed to work.  

Thanks

**Comment by rmind** [comment]
- The limbo list is now managed atomically and is therefore MT-safe. Also, updated README to indicate that the reclamation function takes a list of entries rather than a single entry.
- Implemented Epoch-based reclamation (EBR) algorithm. Might switch G/C mechanism to EBR at some point.
